# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
git_source(:entdec) { |repo_name| "git@code.entropydecelerator.com:#{repo_name}.git" }

gem 'executo', entdec: 'components/executo', branch: :master
