AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "doc/**/*"
    - "log/**/*"

Metrics:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": "[]"
    "%i": "[]"
    "%q": "[]"
    "%Q": "[]"
    "%r": "[]"
    "%s": "[]"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Enabled: false
